services:
  api:
    build: ./backend
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - ./backend/app:/app/app
      - ./backend/credentials.json:/app/credentials.json
      - ./backend/token.json:/app/token.json
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  web:
    build: ./frontend
    ports:
      - '5173:5173'
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev:docker

  db:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=jobtracker
      - POSTGRES_PASSWORD=jobtracker
      - POSTGRES_DB=jobtracker
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
